version: '3.8'
services:
  postgres:
    image: postgres:17.4
    container_name: nestjs_event_booking_API_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: event_booking_API
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: nestjs_event_booking_API-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
